"""NewArhitectureMigration7

Revision ID: a80b57b33d35
Revises: 
Create Date: 2022-07-19 22:32:23.407658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80b57b33d35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    op.add_column('music', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('music_author_fkey', 'music', type_='foreignkey')
    op.create_foreign_key(None, 'music', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_column('music', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music', sa.Column('author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'music', type_='foreignkey')
    op.create_foreign_key('music_author_fkey', 'music', 'authors', ['author'], ['id'], ondelete='CASCADE')
    op.drop_column('music', 'author_id')
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
